#!/bin/sh
#
# Must define LAUNCHER and NPES in the 
# configuration script, in the top level directory
#
# Copyright (c) 2015 Cray Inc.
#
# The contents of this file is proprietary information of Cray Inc.
# and may not be disclosed without prior written consent.
#

echo "====================================================================="
for TEST in `cat $CRAY_TEST_FILE/sma2/sma2_tlist`
do
  $LAUNCHER -n $NPES $CRAY_TEST_BUILD_BIN/sma2/$TEST > $CRAY_TEST_RUN_OUT/sma2/$TEST 2>&1
  exit_status=$?
  grep FAIL $CRAY_TEST_RUN_OUT/sma2/$TEST
  fail_found=$?
  # The test passed if the exit status is 0 and no FAIL messages were found.
  if [[ $exit_status -eq 0 ]] && [[ $fail_found -eq 1 ]] ; then
    echo PASS: NPES: $NPES $TEST
  else
    echo FAIL: NPES: $NPES $TEST
    cat $CRAY_TEST_RUN_OUT/sma2/$TEST
  fi
done
echo "====================================================================="

