#!/bin/sh
#
# Must define LAUNCHER and NPES in the 
# configuration script, in the top level directory

echo "====================================================================="
for TEST in `cat $CRAY_TEST_FILE/smaf/smaf_tlist`
do
  $LAUNCHER -n $NPES $CRAY_TEST_BUILD_BIN/smaf/$TEST > $CRAY_TEST_RUN_OUT/smaf/$TEST 2>&1
  exit_status=$?
  grep FAIL $CRAY_TEST_RUN_OUT/smaf/$TEST
  fail_found=$?
  # The test passed if the exit status is 0 and no FAIL messages were found.
  if [[ $exit_status -eq 0 ]] && [[ $fail_found -eq 1 ]] ; then
    echo PASS: NPES: $NPES $TEST
  else
    echo FAIL: NPES: $NPES $TEST
  fi
done
echo "====================================================================="

